### ISSUE TITLE
Unable to run 'ember server'

### ISSUE THREAD

**Issue by sunblade** [transitland/dispatcher#180]
I am trying to run transitland, and actually I have an issue with dispatcher:

ember-cli: 2.11.0
node: 6.9.4
os: linux x64

```
sunblade@debian:~/dispatcher$ ember server

DEPRECATION: Overriding init without calling this._super is deprecated. Please call this._super(), addon: `ember-cli-font-awesome`
    at Function.Addon.lookup (/home/sunblade/dispatcher/node_modules/ember-cli/lib/models/addon.js:996:27)
Cannot read property 'nodeModulesPath' of undefined
TypeError: Cannot read property 'nodeModulesPath' of undefined
    at DependencyVersionChecker.NPMDependencyVersionChecker (/home/sunblade/dispatcher/node_modules/ember-cli-version-checker/index.js:137:32)
    at VersionChecker.for (/home/sunblade/dispatcher/node_modules/ember-cli-version-checker/index.js:41:12)
    at CoreObject.init (/home/sunblade/dispatcher/node_modules/ember-cli-babel/index.js:17:26)
    at CoreObject.superWrapper [as init] (/home/sunblade/dispatcher/node_modules/core-object/lib/assign-properties.js:32:18)
    at CoreObject.Class (/home/sunblade/dispatcher/node_modules/core-object/core-object.js:33:38)
    at /home/sunblade/dispatcher/node_modules/ember-cli/lib/models/addons-factory.js:49:21
    at visit (/home/sunblade/dispatcher/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
    at DAG.topsort (/home/sunblade/dispatcher/node_modules/ember-cli/lib/utilities/DAG.js:137:7)
    at CoreObject.initializeAddons (/home/sunblade/dispatcher/node_modules/ember-cli/lib/models/addons-factory.js:44:11)
    at CoreObject.initializeAddons (/home/sunblade/dispatcher/node_modules/ember-cli/lib/models/addon.js:223:38)
```

Any idea how to solve this issue.

**Comment by drewda** [comment]
Thanks for your interest in the Transitland Dispatcher!

Dispatcher is still built using:
- Ember CLI 2.5.1: https://github.com/transitland/dispatcher/blob/master/package.json#L28
- Node 0.10.33: https://github.com/transitland/dispatcher/blob/master/circle.yml#L3

We're certainly overdue to upgrade these dependencies. In the meantime, do give a try with these older versions. We're also always open to PRs to upgrade.

**Comment by sunblade** [comment]
Thanks for answer.

I will try to use suggested versions. 
Today I have started dispatcher by changing 'ember-cli-font-awesome' with version 2.2.0 cloned from git repo.
I will give a feedback after testing
